# Build and compile the frontend
FROM node:latest as build-stage

WORKDIR /app
COPY package*.json /app/
RUN npm install --legacy-peer-deps

COPY ./ /app/
RUN npm run build -- --output-path=./dist/out --configuration production

# Get the compiled app ready to be served with Nginx
FROM nginx:latest
ARG BACKEND_KEY
ENV BACKEND_KEY=$BACKEND_KEY

COPY --from=build-stage /app/dist/out/ /usr/share/nginx/html
COPY ./nginx-configuration.conf /etc/nginx/conf.d/default.conf

RUN sed -i "s/BACKEND_KEY;/$BACKEND_KEY;/g" /etc/nginx/conf.d/default.conf
